# Generated by Django 4.2.3 on 2023-08-02 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_assignmentview_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Assignment',
            new_name='AssignmentStudent',
        ),
        migrations.DeleteModel(
            name='AssignmentView',
        ),
        migrations.AlterField(
            model_name='assignmentstudent',
            name='assignId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.assignmentteacher'),
        ),
    ]
