# Generated by Django 4.2.3 on 2023-08-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignmentteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignmentteacher',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AssignmentStudent',
        ),
        migrations.DeleteModel(
            name='AssignmentTeacher',
        ),
    ]
