# Generated by Django 4.2.3 on 2023-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20230802_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='course',
            name='field',
            field=models.CharField(choices=[('BASICS-PROGRAMMING', 'Basics Programming'), ('FRONT-END', 'Front End'), ('BACK-END', 'Back End'), ('FULLSTACK', 'Full stack'), ('MOBILE-DEVELOPMENT', 'Mobile Development'), ('GRAPHIC-DESIGN', 'Graphic Design'), ('MOTION-GRAPHICS', 'Motion Graphics'), ('MARKETING', 'Marketing'), ('PHOTOGRAPHY', 'Photography'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
