# Generated by Django 4.2.3 on 2023-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='field',
            field=models.CharField(choices=[('COMPUTER-SCIENCE', 'Computer Science'), ('FRONT-END', 'Front End'), ('BACK-END', 'Back End'), ('FULLSTACK', 'Full stack'), ('MOBILE-DEVELOPMENT', 'Mobile Development'), ('GRAPHIC-DESIGN', 'Graphic Design'), ('MOTION-GRAPHICS', 'Motion Graphics'), ('MARKETING', 'Marketing'), ('PHOTOGRAPHY', 'Photography'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
