# Generated by Django 4.2.3 on 2023-08-03 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_timestamp_message_time_and_date_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
