# Generated by Django 4.2.3 on 2023-08-03 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_receiver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time_and_date',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
