# Generated by Django 4.2.3 on 2023-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course_rate',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
