# Generated by Django 4.2.3 on 2023-07-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField(default='https://')),
                ('description', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('Technology', 'Technology'), ('Programming', 'Programming'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Data Science', 'Data Science'), ('Networking', 'Networking'), ('Cybersecurity', 'Cybersecurity'), ('Game Development', 'Game Development'), ('Other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='library/book/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
