# Generated by Django 4.2.3 on 2023-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_contactus_name_contactus_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
