# Generated by Django 4.2.3 on 2023-08-10 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
