# Generated by Django 4.2.3 on 2023-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_studentassignment_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='', upload_to='assignments/%d'),
            preserve_default=False,
        ),
    ]
