# Generated by Django 4.2.3 on 2023-08-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_alter_examresult_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
