# Generated by Django 4.2.3 on 2023-08-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_examresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
